title: Benjamin Tozier's Projects
description: A gathering of various projects that I've worked on, as well as plans for new ones.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-them